# name: Deploy to GitHub Pages

# on:
#   push:
#     branches:
#       - main

# permissions:
#   contents: write

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: "20"
#           cache: "npm"

#       - name: Install dependencies
#         run: npm ci

#       - name: Build
#         run: npx ng build Politicode --configuration production --base-href /politicode-website/

#       - name: Deploy to GitHub Pages
#         uses: peaceiris/actions-gh-pages@v4
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ./dist/politicode/browser
#           enable_jekyll: false

name: Deploy Angular to O2Switch

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --configuration production

      - name: Deploy via FTP to O2Switch
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.ton-domaine.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/nom-de-ton-app/browser/
          server-dir: /public_html/
